[package]
name = "reflector-derive"
edition = "2024"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["full", "visit-mut", "visit"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
