[package]
name = "reflector-serde"
edition = "2024"
version.workspace = true

[dependencies]
reflector = { path = "../reflector" }
serde = { version = "1.0.219", default-features = false }

[dev-dependencies]
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }